site_name: My Docs

theme:
  name: material


markdown_extensions:
- toc:
    permalink: true
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true


plugins:
- markdown-exec:
    ansi: required
